# Generated by Django 4.0.1 on 2022-03-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category_created_time_category_update_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_time',)},
        ),
    ]
