# Generated by Django 4.0.1 on 2022-03-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(default='Linke Tıkla ve Okumaya Başla', max_length=200),
        ),
    ]
