# Generated by Django 4.0.1 on 2022-03-23 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_comment_author_remove_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
