# Generated by Django 4.0.1 on 2022-03-24 12:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_comment_email_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ayar İsmi')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('smtpserver', models.CharField(blank=True, max_length=50, null=True)),
                ('smtpemail', models.CharField(blank=True, max_length=50, null=True)),
                ('smtppassword', models.CharField(blank=True, max_length=50, null=True)),
                ('smtpport', models.CharField(blank=True, max_length=9, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='SiteIcon/%Y/%m/%d/')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('aboutus', ckeditor.fields.RichTextField()),
                ('status', models.PositiveIntegerField(choices=[('embed', 'Yayınla'), ('development', 'Yayından Kaldır')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
