# Generated by Django 4.0.1 on 2022-03-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_aboutus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='SiteConfig',
        ),
    ]
