# Generated by Django 4.0.1 on 2022-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_rename_aboutus_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='status',
            field=models.CharField(choices=[('embed', 'Yayınla'), ('development', 'Yayından Kaldır')], max_length=15),
        ),
    ]
